### ISSUE TITLE
Add sass.cr to LibSass showcase

### ISSUE THREAD

**Issue by donovanglover** [straight-shoota/sass.cr#2]
Thanks for spending the time to make this shard!

This repository (and the Crystal language!) could gain more popularity if it was added to the LibSass showcase here: https://sass-lang.com/libsass

Should be as easy as adding a few lines to the file at:

https://github.com/sass/sass-site/blob/master/source/libsass.html.haml

**Comment by straight-shoota** [comment]
Sounds good. I have seen that page before...but didn't want to push this too fast when it was brand new.
Feel free to go ahead, or I'll try to get it done next week.

**Comment by donovanglover** [comment]
I opened a pull request here: sass/sass-site#201

**Comment by donovanglover** [comment]
Unfortunately, the pull request is still open for `sass/sass-site`. It looks like `sass/libsass` has a [list of implementations](https://github.com/sass/libsass/blob/master/docs/implementations.md) as well (and is more active). Would you like to make the pull request?

**Comment by straight-shoota** [comment]
Thanks for keeping tabs on it. I've opened sass/libsass#2574

**Comment by donovanglover** [comment]
Since both pull requests have been merged, I'm closing this issue now. Great to see sass.cr added!
